---
# 3proxy configuration
socks_external_port: 443

# Docker compose configuration
image_tag: "1"
proxy_port: 3128
socks_port: 1080
max_connections: 100
primary_resolver: "77.88.8.8"
secondary_resolver: "8.8.8.8"
