---
allowed_network: "79.98.8.0/21"
docker_apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_repository: >-
  deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
  https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable
